baseurl = "https://www.example.org/"
title = "Code Infinity Loop"
copyright = "Copyright &copy; 2019 - Code Infinity"
canonifyurls = true
theme = "kiera"
themesDir = "themes"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = ""
    github = "funkydan2"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "ds_says"
    instagram = ""

[params]
    tagline = "Infinite thoughts which is not perfect and doestn't end"
